language: objective-c
osx_image: xcode9

script:
    - xcodebuild clean build -project sample-with-framework/applozicdemo.xcodeproj -scheme applozicdemo -destination "platform=iOS Simulator,name=iPhone 7,OS=11.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
